FROM node:21-alpine
WORKDIR /app

RUN apk add --no-cache libc6-compat

COPY .yarn/releases ./.yarn/releases
COPY package.json yarn.lock .yarnrc.yml ./

RUN yarn install

COPY . ./

EXPOSE 3000

CMD ["yarn", "dev"]
