services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.development
    ports:
      - "3000:3000"
    volumes:
      - ./src:/app/src
      - ./public:/app/public
      - ./next-env.d.ts:/app/next-env.d.ts
      - ./next.config.js:/app/next.config.js
      - ./package.json:/app/package.json
      - ./tsconfig.json:/app/tsconfig.json
