import './globals.css';
import { LoginGuard } from './login-guard';
import StoreProvider from './StoreProvider';

import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <StoreProvider>
        <body>
          <LoginGuard>{children}</LoginGuard>
        </body>
      </StoreProvider>
    </html>
  );
}
