import { Footer } from '#/components/templates/Footer';
import { Header } from '#/components/templates/Header';
import './globals.css';
import { SignupGuard } from './signup-guard';

import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <SignupGuard />
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
