name: Discord notification
run-name: Discord notification for ${{ github.ref_name }} by ${{ github.actor }} at ${{ github.ref }}

on: deployment_status

jobs:
  notify:
    name: Notify
    runs-on: ubuntu-latest
    steps:
      - name: Post Actions Status to Discord
        uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
